# Site settings
title: Dr. Tilmann Steinmetz
name: Tilmann Steinmetz

# Build settings
markdown: kramdown

#User specific content
#Links that will appear in the navbar
primarylinks:
 - title: Blog
   url: https://bird70.github.io/ask-the-data
 - title: GitHub
   url: https://github.com/bird70
 - title: LinkedIn
   url: https://www.linkedin.com/in/tilmann-steinmetz-489b062a/
 
#Any buzzword skills you want to include
skills:
 - Technical Architecture
 - ArcGIS
 - Python
 - R
 - AWS
 - SQL
 - FME
 - ETL
 - MongoDB
 - PowerBI
 - REST
 - JavaScript
 - React
 - Machine learning
 - Deep Learning

#Blogfeed is optional - including this will add JS to call the feed and populate blog list
#blogfeed: https://automateddeveloper.blogspot.com/feeds/posts/default?alt=json

#Work experience is required
roles:
 - title: Principal Technician - GIS Data
   start: 2025
   end: Ongoing
   employer: New Zealand Earth Sciences Institute NZESI (formerly NIWA)
   description: Worked on data warehouse/ data platform and GIS cloud migration around the time NZ organisations NIWA and GNS merged (various tasks around ETL using AWS, FME, Python)  
 - title: Principal Technician - GIS Data
   start: 2021
   end: 2025
   employer: NIWA National Institute of Water and Atmospheric Research NZ
   description: Worked on implementing NIWAs state-of-the-art, self-service GIS platform that can be used for internal and external project needs, such as data collection and management, analysis and sharing with web applications. </br>Over the past 3 years, one of my main tasks has been to design and establish a modern Geospatial Infrastructure which allows all ~700 NIWA staff to self-service their GIS needs. </br>This has involved a number of large changes, including moving from ArcGIS Server to a full ArcGIS Enterprise including a Raster Analytics platform, moving several SDE databases to new servers with minimal disruption and migrating our ~120 ArcGIS Desktop users to newer software, particularly ArcGIS Pro. Without the benefit of having a GIS team, much of the actual technical migration has been provided by third-party technical consultants while I have acted as the 'project owner'. At the same time, we have run some key projects that have championed the use of the new platform, among them users of raster analytics and many members of the field data teams. My current role is to enable more projects to use the new platform by building applications in order to showcase technical and organizational workflows, support users and act as intermediary between NIWA-internal IT, users and third-party contractors. I also work on improving many of the operational aspects of routinely running geospatial workflows for many projects in a shared platform, and monitoring platform use and performance. I develop datasets and applications in consultation with staff and management and train users in understanding the workflows to use these as well as make their own, using best-practice recommendations.
 - title: GIS Data Analyst and Admin
   start: 2017
   end: 2021
   employer: NIWA
   description: I was in charge of spatial data and GIS infrastructure at NIWA, based in Wellington.
 - title: Senior GIS Consultant
   start: 2010
   end: 2017
   employer: Eagle Technology Group Ltd Esri New Zealand Distributor
   description: Professional Services Team, Scoped, Analysed, Designed and Implemented Esri-based geospatial solutions for national and local government as well as research and private customers. These solutions often require an integration of Esri GIS with a variety of enterprise systems, like asset managment system or CRM for their spatial enablement. </br>As a Technical Advisor, my activities encompassed from pre-sales strategy to maintenance and training.
 - title: GIS Analyst Consultant
   start: 2007
   end: 2010
   employer: DLR DFD German Aerospace Center Oberpfaffenhofen Munich 
   description: DLR DFD German Aerospace Center, German Remote Sensing data center formed part of a large consortium of institutions building a tsunami early warning system for Indonesia</br>The system is in place since April 2010 and being used by the Indonesian national warning center.
 - title: Geologist
   start: 1998
   end: 1998
   employer: Sakosta Lomex Munich
   description: Worked in the exploration and remediation of petroleum-contaminated sites; I sampled sites, observed remediation, managed logistics, wrote reports.

   
#Education is required
education:
 - level: Dr Rer Nat PhD
   date: 2003
   subject: Environmental Geology and Geoinformatics
   school: Martin-Luther University Halle-Wittenberg Germany

#This section is optional (as is the image link below)
coursera:
   profileurl: https://www.coursera.org/user/2a881d13ed3bab045c54df7d0eb810f4
   courses:
    - title: Amazon Web Services AWS Cloud Solutions Architect Associate Certificate
      link: https://www.credly.com/badges/a0cdd8ae-40c7-4c78-a5f4-4dc677bfb167/public_url
      optionalimage: https://images.credly.com/size/200x200/images/0e284c3f-5164-4b21-8660-0d84737941bc/image.png
      date: April 29, 2025
    - title: Advanced Data Analytics (Google)
      link: https://www.credly.com/badges/0652e894-8cef-489c-8f37-2aa9cdb4f00e
      optionalimage: https://images.credly.com/size/340x340/images/9267a387-1a51-4ebe-8c05-976a5ec4c3d0/image.png
      date: December 9, 2023
    - title: DevOps, DataOps, MLOps
      link: https://www.coursera.org/account/accomplishments/verify/LCWBZZED4TD4
      optionalimage:
      date: June 15,  2024
    - title: Data Science Foundations - Statistical Inference by University of Colorado Boulder on Coursera.
      link: https://www.coursera.org/account/accomplishments/specialization/YUJ28NAX4KTQ
      optionalimage:
      date: June 27, 2025
    

#This section is optional - embeds slideshows from speakerdeck
# to get the speakerdeck ID copy the embed code and look for the data-it attribute
# speakerdeck:
#    profileurl: https://speakerdeck.com/robhinds
#    talks:
#     - title: Product Management for Engineers
#       speakerdeckId: 94f0070c4e434ec79fe9b4eb2cb574e0
#       conference: API Conference, Berlin 2018
#     - title: Agile Machine Learning - from Theory to Production
#       speakerdeckId: ec84f2f56e9743afb0675b1eeeb6b6ce
#       conference: W-JAX Conference, Munich 2017 (London 2017)

#List of interesting Github repo/projects to include - optional
github:
 - bird70/MDCS_mosaic_dataset_config_scripts
 - bird70/geospatial_ETL_pipeline
 - bird70/ArcGIS-Metadata-Tools
 - bird70/AWS_ArcGIS_Lambda_Layer
 - bird70/AWS_ArcGIS_Lambda_ImageService
 - bird70/AWS_NetCDF_2_ArcGIS_Online_Feature
 

##Stackoverflow flair is optional
# stackoverflow:
#    profileurl: https://stackoverflow.com/users/258813/rhinds
#    flairimageurl: https://stackoverflow.com/users/flair/258813.png

intro: |
  I am a researcher, spatial data administrator, data engineer and data scientist. I work with remote sensing data, flood and flow data, bathymetric as well as biology data. 
  </br>
  I frequently build web applications to make those data available publicly. Finding and implementing the right data model, which also meets requirements, is one of the critical and often challenging parts of my role.</br>
  </br>
  I work with Esri ArcGIS Software most of the time to build the applications. What's cool about using Esri's web app stack is that often there is actually almost no code involved in making the client-side application - although sometimes, coding custom apps, or widgets that can be added to the app, may be required. 
  While I make applications, NIWA as an organisation provides GIS to all staff, as a self-service facility, and I'm also acting as the GIS administrator, including understanding and meeting all users' requirements. Scripting and automation are a big part of what I do.</br>
  </br>
  I have also facilitated the roll-out of the ArcGIS environment which the organization uses nowadays: ArcGIS Pro, ArcGIS StoryMaps, ArcGIS FieldMaps and Survey123 (for mobile/ field workers), in combination with a custom raster analytics ArcGIS Enterprise Platform and ArcGIS Online. We use a variety of different data technologies to hold the data, among them Esri SDE databases in Microsoft SQLServer and the Esri Data Store component of ArcGIS Enterprise and ArcGIS Online. ArcGIS Monitor is used to track performance and usage.</br>


#An additional info freetext section is optional at the bottom of the page - can be text or HTML
additionalinfo: |
   <strong>Te Reo Maori</strong>: I have studied Te Reo Maori two semesters in a remote learning course at Te Wananga oo Raukawa, Otaki, called Huia Te Reo 1 and 2. I love to learn languages!<br/><br/>
    <strong>Birdwatching</strong>: I am a keen birdwatcher and have been involved in eBird, which is a citizen science project to map the distribution of birds globally and in New Zealand. I have also developed a mobile app called NZBirder to help bird watchers record their sightings and share them with others.<br/><br/>
mobile:
  apps:
    - name: NZBirder
      platform: iOS
      url: https://docs.google.com/document/d/1Zl011iygWqg3w8ecJw78bPZsmENPtG86ZAvMtLHfxzw/pub
      description: NZBirder is a mobile app for iPhone that allows bird watchers to record their sightings and share them with others. It includes features such as a bird identification guide, location tracking, and the ability to upload photos of birds.
