# Site settings
title: Dr. Tilmann Steinmetz
name: Tilmann Steinmetz

# Build settings
markdown: kramdown

#User specific content
#Links that will appear in the navbar
primarylinks:
 - title: Blog
   url: https://bird70.github.io/ask-the-data
 - title: GitHub
   url: https://github.com/bird70
 - title: LinkedIn
   url: https://www.linkedin.com/in/tilmann-steinmetz-489b062a/
 
#Any buzzword skills you want to include
skills:
 - ArcGIS
 - Python
 - Tableau
 - SQL
 - REST
 - JavaScript
 - React
 - Technical Architecture
 - Machine learning

#Blogfeed is optional - including this will add JS to call the feed and populate blog list
#blogfeed: https://automateddeveloper.blogspot.com/feeds/posts/default?alt=json

#Work experience is required
roles:
 - title: Principal Technician - GIS Data
   start: 2021
   end: Ongoing
   employer: NIWA National Institute of Water and Atmospheric Research NZ
   description: Worked on implementing NIWAs state-of-the-art, self-service GIS platform that can be used for internal and external project needs, such as data collection and management, analysis and sharing with web applications. </br>Over the past 3 years, one of my main tasks has been to design and establish a modern Geospatial Infrastructure which allows all ~700 NIWA staff to self-service their GIS needs. </br>This has involved a number of large changes, including moving from ArcGIS Server to a full ArcGIS Enterprise including a Raster Analytics platform, moving several SDE databases to new servers with minimal disruption and migrating our ~120 ArcGIS Desktop users to newer software, particularly ArcGIS Pro. Without the benefit of having a GIS team, much of the actual technical migration has been provided by third-party technical consultants while I have acted as the 'project owner'. At the same time, we have run some key projects that have championed the use of the new platform, among them users of raster analytics and many members of the field data teams. My current role is to enable more projects to use the new platform by building applications in order to showcase technical and organizational workflows, support users and act as intermediary between NIWA-internal IT, users and third-party contractors. I also work on improving many of the operational aspects of routinely running geospatial workflows for many projects in a shared platform, and monitoring platform use and performance. I develop datasets and applications in consultation with staff and management and train users in understanding the workflows to use these as well as make their own, using best-practice recommendations.
 - title: GIS Data Analyst and Admin
   start: 2017
   end: 2021
   employer: NIWA
   description: I was in charge of spatial data and GIS infrastructure at NIWA, based in Wellington.
 - title: Senior GIS Consultant
   start: 2010
   end: 2017
   employer: Eagle Technology Group Ltd Esri New Zealand Distributor
   description: Professional Services Team, Scoped, Analysed, Designed and Implemented Esri-based geospatial solutions for national and local government as well as research and private customers. These solutions often require an integration of Esri GIS with a variety of enterprise systems, like asset managment system or CRM for their spatial enablement. </br>As a Technical Advisor, my activities encompassed from pre-sales strategy to maintenance and training.
 - title: GIS Analyst Consultant
   start: 2007
   end: 2010
   employer: DLR DFD German Aerospace Center Oberpfaffenhofen Munich 
   description: DLR DFD German Aerospace Center, German Remote Sensing data center formed part of a large consortium of institutions building a tsunami early warning system for Indonesia</br>The system is in place since April 2010 and being used by the Indonesian national warning center.
 - title: Geologist
   start: 1998
   end: 1998
   employer: Sakosta Lomex Munich
   description: Worked in the exploration and remediation of petroleum contaminated sites; I sampled sites, observed remediation, managed logistics, wrote reports.

   
#Education is required
education:
 - level: Dr Rer Nat PhD
   date: 2003
   subject: Environmental Geology and Geoinformatics
   school: Martin-Luther University Halle-Wittenberg Germany

#This section is optional (as is the image link below)
coursera:
   profileurl: https://www.coursera.org/user/2a881d13ed3bab045c54df7d0eb810f4
   courses:
    - title: Advanced Data Analytics (Google)
      link: https://www.coursera.org/professional-certificates/google-advanced-data-analytics
      optionalimage: https://www.credly.com/badges/0652e894-8cef-489c-8f37-2aa9cdb4f00e/public_url
      date: December 9, 2023

#This section is optional - embeds slideshows from speakerdeck
# to get the speakerdeck ID copy the embed code and look for the data-it attribute
# speakerdeck:
#    profileurl: https://speakerdeck.com/robhinds
#    talks:
#     - title: Product Management for Engineers
#       speakerdeckId: 94f0070c4e434ec79fe9b4eb2cb574e0
#       conference: API Conference, Berlin 2018
#     - title: Agile Machine Learning - from Theory to Production
#       speakerdeckId: ec84f2f56e9743afb0675b1eeeb6b6ce
#       conference: W-JAX Conference, Munich 2017 (London 2017)

#List of interesting Github repo/projects to include - optional
github:
 - bird70/MDCS_mosaic_dataset_config_scripts
 


# #Stackoverflow flair is optional
# stackoverflow:
#    profileurl: https://stackoverflow.com/users/258813/rhinds
#    flairimageurl: https://stackoverflow.com/users/flair/258813.png

intro: |
  I'm a researcher and spatial data administrator. I currently work with remotely sensed imagery, flood and flow data, bathymetric as well as biology data. I frequently build web applications to make those data available publicly, and finding and implementing the right data model which meets requirements is one of the more challenging parts of my role.</br>
  I work with Esri ArcGIS Software most of the time to build the applications and interestingly, often there is actually almost no code involved in making the client-side application. While I make applications, NIWA as an organisation provides GIS to the entire organisation, as a self-service facility, and I'm also acting as the GIS administrator, including understanding and meeting all users' requirements. This can only be accomplished using scripting and automation.</br>
  I have also facilitated the roll-out of the ArcGIS environment which NIWA uses nowadays: ArcGIS Pro, ArcGIS FieldMaps and Survey123, in combination with a custom raster analytics ArcGIS Enterprise Platform and ArcGIS Online. We use a variety of different data technologies to hold the data, among them Esri SDE databases in Microsoft SQLServer and the Esri Data Store component of ArcGIS Enterprise.


#An additional info freetext section is optional at the bottom of the page - can be text or HTML
additionalinfo: |
   <strong>Web Development</strong>: Through building ArcGIS web applications, I have also worked with various client side technology. Recently I have used React with ArcGIS ExperienceBuilder applications <br/><br/>
   <strong>Te Reo Maori</strong>: I have studied Te Reo Maori two semesters in a remote learning course at Te Wananga oo Raukawa, Otaki, called Huia Te Reo 1 and 2. <br/><br/>
   <strong>Mobile App</strong>: I have made an iPhone app called NZBirder, using Objective-C which was available through the Apple app store for a number of years.